### PR TITLE
Spec by operation

### LINKED ISSUE #21: Enable rendering components for multiple specs on a single page.
Currently I have something like this on a single markdown page...

```
<script setup lang="ts">
import { useRoute, useData } from 'vitepress'
import { useSidebar, useOpenapi } from 'vitepress-theme-openapi'
import spec from '../swagger/v2.json' with { type: 'json' }
const openapi = useOpenapi()
openapi.setSpec(spec)
const route = useRoute()
const { isDark } = useData()
</script>

<OAOperation operationId="post-users-login" method="post" :isDark="isDark" />
<OAOperation operationId="post-users-refreshToken" method="post" :isDark="isDark" />
```

Further down the page I would like to include a component rendered from the `../swagger/v1.json` spec, however I believe with the current setup that will not be possible.

Ultimately I think this will require passing the openapi into the components? :)

### PR DESCRIPTION
**Pull request by enzonotario**
- Allows multiple specs
- Allows to render Markdown contents
- Allows to configure JSON Viewer deep

Closes #21

### CODE REVIEW

**Comment by addshore** [comment]
While rendering with this, I get the following

```
runtime-core.esm-bundler.js:51 [Vue warn]: Invalid prop: type check failed for prop "content". Expected String with value "undefined", got Undefined  
  at <OAMarkdown content=undefined class="description" > 
  at <OAPath key=0 id="post-users-login" spec= 
{components: {…}, info: {…}, externalDocs: {…}, paths: {…}, openapi: '3.1.0', …}
 > 
  at <OAOperation operationId="post-users-login" spec= 
{components: {…}, info: {…}, externalDocs: {…}, paths: {…}, openapi: '3.1.0', …}
 isDark=false > 
  at <Apis/authentication.md onVnodeMounted=fn<runCbs> onVnodeUpdated=fn<runCbs> onVnodeUnmounted=fn<runCbs> > 
  at <VitePressContent class="vp-doc _apis_authentication" > 
  at <VPDoc key=4 > 
  at <VPContent> 
  at <Layout> 
  at <VitePressApp>
runtime-core.esm-bundler.js:51 [Vue warn]: Unhandled error during execution of render function 
  at <OAMarkdown content=undefined class="description" > 
  at <OAPath key=0 id="post-users-login" spec= 
{components: {…}, info: {…}, externalDocs: {…}, paths: {…}, openapi: '3.1.0', …}
 > 
  at <OAOperation operationId="post-users-login" spec= 
{components: {…}, info: {…}, externalDocs: {…}, paths: {…}, openapi: '3.1.0', …}
 isDark=false > 
  at <Apis/authentication.md onVnodeMounted=fn<runCbs> onVnodeUpdated=fn<runCbs> onVnodeUnmounted=fn<runCbs> > 
  at <VitePressContent class="vp-doc _apis_authentication" > 
  at <VPDoc key=4 > 
  at <VPContent> 
  at <Layout> 
  at <VitePressApp>
vitepress-theme-openapi.es.js:13671 Uncaught (in promise) Error: Input data should be a String
    at xt.parse (vitepress-theme-openapi.es.js:13671:11)
    at xt.render (vitepress-theme-openapi.es.js:13676:49)
    at Proxy.<anonymous> (vitepress-theme-openapi.es.js:15964:23)
    at renderComponentRoot (runtime-core.esm-bundler.js:6322:16)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:4997:46)
    at ReactiveEffect.run (reactivity.esm-bundler.js:177:19)
    at instance.update (runtime-core.esm-bundler.js:5128:16)
    at setupRenderEffect (runtime-core.esm-bundler.js:5138:5)
    at mountComponent (runtime-core.esm-bundler.js:4906:7)
    at processComponent (runtime-core.esm-bundler.js:4860:9)
```

Goig to try and figure out why

**Comment by enzonotario** [comment]
Ups, it's because a change I've added to allows to render Markdown content. I've fixed it. Can you please try again with [latest changes](https://github.com/enzonotario/vitepress-theme-openapi/runs/30062155619)

Thanks for reporting!

**Comment by addshore** [comment]
Seems to work perfectly! many thanks!

**Comment by enzonotario** [comment]
@coderabbit summary

**Comment by enzonotario** [comment]
@CodeRabbit review

**Comment by enzonotario** [comment]
@coderabbitai review

**Comment by enzonotario** [comment]
@coderabbitai summary

**Pull request merged**
