### PR TITLE
feat: Schema components

### LINKED ISSUE #18: Request body field (display additional details)
My spec has a bunch of request property descriptions.

Something like this

```
{
  "properties": {
    "password": {
      "description": "Password of the user",
      "type": "string"
    },
    "refreshable": {
      "description": "Generate a refresh token, which expires this many seconds after the access token expiry. Max 31 days",
      "maximum": 2678400,
      "type": "integer"
    }
  }
}
```

Currently, the request body is just specified as a JSON blob

image

How do you think we could / should alter this to include details of descriptions, max, type etc

### PR DESCRIPTION
**Pull request by enzonotario**
- Adds `@scalar/openapi-parser` as Spec Parser.
- Adds support for Request Body
- Adds suport for Security Schemes

Closes #18, #12

### CODE REVIEW

**Comment by enzonotario** [comment]
@addshore I've found the Scalar OpenAPI Parser, so now it's more easy to implement the missing features. Can you please install this preview (`pnpm add https://pkg.pr.new/vitepress-theme-openapi@20`) and check if it's working for you before merging and releasing?

**Comment by addshore** [comment]
Buggy but it works,

On initial page load I see the following. The OAPI component should be rendered where i put the yellow line.

image

The code behind this is ultimately:

```
<h3>Login and get token</h3>

<script setup lang="ts">
import { useRoute, useData } from 'vitepress'
import { useSidebar, useOpenapi } from 'vitepress-theme-openapi'
import spec from '../swagger/v2.json' with { type: 'json' }

const openapi = useOpenapi()
openapi.setSpec(spec)
const route = useRoute()
const { isDark } = useData()
const operationId = "post-users-login"
const method = "post"
// TODO in the spec, detail what refreshable means
spec.paths['/users/login'][method].summary = ''
spec.paths['/users/login'][method].description = 'Login and get a token for further requests.'
</script>
<OAOperation :operationId="operationId" :method="method" :isDark="isDark" />

<h1>Version 1</h1>
```

If I change any part of the `md` file, the page reloads and the component renders correctly.

Such as adding an `x` to the `h3` header.

```
<h3>Login and get tokenx</h3>
```

The component loads

image

With a vue warning

```
authentication.md?import&t=1725003741965:77 [Vue warn]: Invalid prop: type check failed for prop "operationId". Expected String with value "undefined", got Undefined  
  at <OASecurity operation-id=undefined method="post" path="/users/login"  ... > 
  at <OAPath key=0 id="post-users-login" method="post" > 
  at <OAOperation operationId="post-users-login" method="post" isDark=false > 
  at <Apis/authentication.md onVnodeMounted=fn<runCbs> onVnodeUpdated=fn<runCbs> onVnodeUnmounted=fn<runCbs> > 
  at <VitePressContent class="vp-doc _apis_authentication" > 
  at <VPDoc key=4 > 
  at <VPContent> 
  at <Layout> 
  at <VitePressApp>
```

Refreshing the page makes the rendered component vanish again

image

**Comment by addshore** [comment]
Another interesting thing that might help you debug.

On first load, no component

image

On change of the markdown file, the page reloaders and renders the component, but incorrectly?

This `description` of the endpoint is incorrectly set as a `h1` header?

image

A subsequent change of the markdown then correctly sets this string as the description

image

**Comment by enzonotario** [comment]
I fixed the warning `authentication.md?import&t=1725003741965:77 [Vue warn]: Invalid prop: type check failed for prop "operationId". Expected String with value "undefined", got Undefined`.

About the `h1`, only the `summary` is a `h1`, `description` should be just a `div` (where you could put Markdown). I think it's a particular issue that I saw on VitePress, and it's better to have an empty line as separator between Markdown-Vue. Otherwise, please submit a reproduction in this PR (preferable), o in a separate Repo.

Also, consider that you should do any transformations of your Spec **before** set it via `openapi.setSpec()`. I mean:

```
<h3>Login and get token</h3>

<script setup lang="ts">
import { useRoute, useData } from 'vitepress'
import { useSidebar, useOpenapi } from 'vitepress-theme-openapi'
import spec from '../swagger/v2.json' with { type: 'json' }

// TODO in the spec, detail what refreshable means
spec.paths['/users/login'][method].summary = ''
spec.paths['/users/login'][method].description = 'Login and get a token for further requests.'

const openapi = useOpenapi()
openapi.setSpec(spec)

const route = useRoute()
const { isDark } = useData()
const operationId = "post-users-login"
// const method = "post" // <-- It's no needed.

</script>
<OAOperation :operationId="operationId" :isDark="isDark" />

<h1>Version 1</h1>
```

**Comment by addshore** [comment]
I'll try and have a bit more of a play with this branch and figure out why it isn;t rendering for me on first load.
I wonder if it is something to do with the dev server.

Also, good point re the transformations :)

**Comment by enzonotario** [comment]
I'll merge it, since I at least can see that Vercel Preview works fine. If not, just open a new Issue. Thanks!

**Comment by enzonotario** [comment]
> Buggy but it works,

I experimented those issues when updated one of my projects. It's because Scalar OpenApi Parser is async, and causes this issues (I don't know why I didn't experimented it while running `pnpm run dev`, but I reproduced it by sleeping 3s before setting parsed spec).

So, now I've replaced it by a sync alternative. Can you please chek if it's working for you on release `0.0.3-alpha.21` ? It's working fine for me so far.

**Comment by addshore** [comment]
That was it! works well for me now!

**Pull request merged**
